version: '3.9'

services:
  api_contact-book:
    container_name: api_contact-book
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db_contact-book
      - DB_PASSWORD=1234
      - DB=full_stack_challenge
      - DB_USER=dev
      - SECRET_KEY=secr3t
    depends_on:
      db_contact-book:
        condition: service_healthy
    volumes:
      - .:/app
  
  db_contact-book:
    container_name: db_contact-book
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=full_stack_challenge
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d full_stack_challenge"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s